config/routes.rb
Rails.application.routes.draw do
  # Root path
  root 'products#index'

  # Resources
  resources :products
  resources :line_items
  resource  :cart, only: [:index, :show, :delete]
  patch 'update_cart/:id' => 'carts#update', as: 'update_cart'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  accepts_nested_attributes_for :line_items

  def total_quantity
    line_items.any? ? line_items.map { |item| item.quantity }.reduce(:+) : 0
  end

  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def grand_total
    line_items.includes(:product).map { |item| item.product.price * item.quantity }.reduce(:+)
  end
end

app/models/line_item.rb
# == Schema Information
#
# Table name: line_items
#
#  id         :integer          not null, primary key
#  product_id :integer
#  cart_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  quantity   :integer          default(1)
#
# Indexes
#
#  index_line_items_on_cart_id     (cart_id)
#  index_line_items_on_product_id  (product_id)
#

class LineItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  image_url   :string
#  price       :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Product < ActiveRecord::Base
  before_destroy :ensure_not_referenced_by_line_items
  has_many :line_items

  private

  def ensure_not_referenced_by_line_items
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line items present.')
      return false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  add_flash_types :success, :warning
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:show]

  def show
  end

  def update
    @cart = Cart.find(session[:cart_id])
    if @cart.update(cart_params)
      redirect_to cart_path, success: 'Cart updated.'
    else
      render :show
    end
  end

  private

  def cart_params
    params.require(:cart).permit(line_items_attributes: [:quantity, :id])
  end
end

app/controllers/concerns/current_cart.rb
module CurrentCart
  extend ActiveSupport::Concern

  private

  def set_cart
    @cart = Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    @cart = Cart.create
    session[:cart_id] = @cart.id
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:create]

  def create
    @line_item = @cart.add_product(params[:product_id])
    if @line_item.save
      redirect_to cart_path, success: 'Item was added to current cart.'
    else
      render 'products/index'
    end
  end

  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy
    redirect_to cart_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  def index
    @products = Product.all
  end

  private

  def invalid_cart
    session[:cart_id] = nil
    redirect_to products_path, warning: 'Invalid cart.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/line_items/_line_item.html.erb
<%= content_tag_for :tr, line_item do %>
  <td class="col-md-4"><%= line_item.product.name %></td>
  <td class="col-md-3"><%= field.number_field :quantity, class: 'quantity form-control input-sm' %></td>
  <td class="col-md-2"><%= number_to_currency(line_item.product.price) %></td>
  <td class="col-md-2"><%= number_to_currency(line_item.quantity * line_item.product.price) %></td>
  <td class="col-md-1">
    <%= link_to line_item_path(line_item), method: :delete, class: 'btn btn-xs', turboboost: true, data: { confirm: 'Are you sure?' } do %>
      <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
    <% end %>
  </td>
<% end %>

app/views/carts/line_items/_line_items.html.erb
<%= form_for cart, url: update_cart_path(cart), turboboost: true do |f| %>
  <table class="table">
    <thead>
      <tr>
        <th>Robot Name</th>
        <th>Quantity</th>
        <th>Unit Price</th>
        <th>Total</th>
      </tr>
    </thead>
    <tbody>
    <%= f.fields_for :line_items, cart.line_items.includes(:product).order(created_at: 'desc') do |field| %>
      <%= render 'carts/line_items/line_item', line_item: field.object, field: field %>
    <% end %>
      <tr>
        <td></td>
        <td>
          <%= button_tag type: 'submit', class: 'btn btn-info btn-xs', value: 'button' do %>
            <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span> Update Cart
          <% end %>
        </td>
        <td><strong>Grand Total</strong></td>
        <td><strong><%= number_to_currency(cart.grand_total) %></strong></td>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/carts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">Shopping Cart</h1>
      <% if @cart.line_items.any? %>
        <%= render 'carts/line_items/line_items', cart: @cart %>
        <hr>
        <%= link_to products_path, class: 'btn btn-default' do %>
          <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span> Back to Store
        <% end %>
        <button class="btn btn-success pull-right">
          Checkout Now <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
        </button>
      <% else %>
        <h5>Your cart is currently empty</h5>
        <hr>
        <%= link_to products_path, class: 'btn btn-default' do %>
          <span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span> Back to Store
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |key, message| %>
  <div class="alert alert-<%= key %> alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Robot Shop</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Store', products_path %></li>
        <li>
          <%= link_to cart_path do %>
            <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
            Cart (<%= session[:cart_id].nil? ? 0 : Cart.find(session[:cart_id]).total_quantity %> items)
          <% end %>
        </li>
        <li><a href="#">Login</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Robot Shop</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="container" id="flash">
      <%= render 'layouts/flash' %>
    </div>
    <div id="site-content">
      <%= yield %>
    </div>
    <footer class="footer">
      <div class="container">
        <p class="muted">&copy; 2015 Robot Shop, Inc</p>
      </div>
    </footer>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/line_items/create.js.erb
$('#flash').html('<%= j render partial: 'layouts/flash' %>');

app/views/products/_product.html.erb
<div class="col-md-3 col-sm-6">
  <span class="thumbnail product">
    <img src=<%= product.image_url %>>
    <h4><%= product.name %></h4>
    <div class="ratings">
      <span class="glyphicon glyphicon-star"></span>
      <span class="glyphicon glyphicon-star"></span>
      <span class="glyphicon glyphicon-star"></span>
      <span class="glyphicon glyphicon-star"></span>
      <span class="glyphicon glyphicon-star-empty"></span>
    </div>
    <p><%= truncate(product.description) %></p>
    <hr>
    <div class="row">
      <div class="col-md-6 col-xs-6">
        <p class="price"><%= number_to_currency(product.price) %></p>
      </div>
      <div class="col-md-6 col-xs-6">
        <%= button_to 'Add to Cart', line_items_path(product_id: product.id), class: 'btn btn-success buy', turboboost: true %>
      </div>
    </div>
  </span>
</div>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">Robot Index</h1>
    </div>
  </div>
  <div class="row">
    <%= render partial: 'product', collection: @products %>
  </div>
</div>